### ISSUE TITLE
Javascript dependencies

### ISSUE THREAD

**Issue by Matt-Yorkley** [fly-apps/rails-nix#13]
Whew, the NixOS learning curve is pretty steep!

I had a crack at a basic working example integrating Yarn and Webpacker in a branch here: https://github.com/fly-apps/rails-nix/compare/main...Matt-Yorkley:webpacker-trial

**Issues**

There were a couple of Webpacker-related issues related to the fact that the container has no internet access during the build phase. The first is that webpacker inserts itself into the precompile process in Rails and by default it checks to see if `yarn` is available by calling `yarn --version` and errors out if it doesn't get a result. I resolved this by including `yarn` (the nix package) in the build deps.

The second issue is that Webpacker tries to run `yarn install` by default before compiling, which isn't possible during the build phase and throws a fatal error (network error). There wasn't much room to manuever here as the yarn version available via nix is `1.x.x`, which doesn't have nice ENV vars for changing it's behaviour (that's in `2.x.x`), but luckily Webpacker skips calling yarn [here](https://github.com/rails/webpacker/blob/f1b06c7fd5bc4b7fc7128742d1078466b94af71f/lib/webpacker/runner.rb#L13) if `WEBPACKER_NODE_MODULES_BIN_PATH` is provided with a valid path to `node_modules/.bin`, which was a viable option.

**Notes**

Since this required some quite specific interventions, I'm imagining this would need to handle things slightly differently depending on the JS bundling option used, eg: Webpacker, Vite, Esbuild, jsbundling-rails, Importmaps, etc. 

Each npm package is nixified here via `yarn2nix`, the command for updating `yarn.nix` is: `yarn2nix > yarn.nix`. A reference to the store is symlinked into the build at the end so the app can find it.

**Comment by jsierles** [comment]
I believe it's possible to tell Rails to skip yarn install on precompile. I have an app where I did this with:

```
Rake::Task["assets:precompile"].clear_prerequisites
Rake::Task["assets:precompile"].enhance [ "environment" ]
```

The build should have internet access as it needs to pull things from Nix cache. Where are you running the build?

> Since this required some quite specific interventions, I'm imagining this would need to handle things slightly differently depending on the JS bundling option used, eg: Webpacker, Vite, Esbuild, jsbundling-rails, Importmaps, etc.

Yep, this is OK. Webpacker is by far the most complex, so the others should be simpler. For now, maybe it's best to keep 'stable' branches for each approach?

**Comment by jsierles** [comment]
Now we have a better handle on this, we can open specific issues as we venture into node modules support.
