### ISSUE TITLE
Custom Ruby / Bundler versions

### ISSUE THREAD

**Issue by Matt-Yorkley** [fly-apps/rails-nix#14]
I had a quick look at getting `default.nix` to build with arbitrary Ruby versions here: https://github.com/fly-apps/rails-nix/compare/main...Matt-Yorkley:versions

I'm not sure if that's the right way to do it, but it builds and successfully runs the app on the latest Ruby `3.1.1` (which was just released a few days ago). It feels like it should be extracted into a nice module somehow, but I'm not sure what that looks like :sweat_smile: 

To be useful for a range of Rails apps, it'll ultimately need the ability to specify a Ruby dot-version, specify a _bundler_ dot-version, then build / fetch them both, then install all gems through bundix using the exact Ruby and bundler versions.

**Comment by jsierles** [comment]
Nice, this looks about right. We'll probably want to extract these into a separate repo where we build and upload to a binary cache. I'll open a separate issue to try to outline what I think we can try.

**Comment by Matt-Yorkley** [comment]
Just a note on some of the details of building Ruby versions (which might be a bit much at this early stage, but could be a consideration later): there's a couple of build flags that are quite popular and might be in demand if the Rails/Nix thing takes off, related to increasing Ruby's performance/speed. The first is the `--with-jemalloc` flag for switching out the default memory allocator, and the second is the new flag for enabling YJIT (which is now available in Ruby, but I think still disabled by default).

**Comment by jsierles** [comment]
Yeah, I was thinking about that. We definitely want jemalloc enabled for every version, so we should start thinking about it. @samueldr can probably get us into shape here once the build stuff is sorted. I'm going to create a repo for the nix stuff to be extracted to. We can start plopping things like this in there.

**Comment by Matt-Yorkley** [comment]
There are some bits built in to the `pkgs.ruby` implementation for handling `jemalloc` already :ok_hand: But yeah the opt-in or opt-out YJIT thing will be in demand and that makes things a bit more complex if you want to offer that.

**Comment by jsierles** [comment]
Now this is being moved into https://github.com/fly-apps/nix-base, we can open more specific tickets there.
