### ISSUE TITLE
Gems are rebuilt on gemdir input change

### ISSUE THREAD

**Issue by samueldr** [fly-apps/rails-nix#17]
See:

 - https://github.com/fly-apps/rails-nix/tree/fix/gems-isolation

Since the `gemdir` is the `src` dir, any change will also cause a *minor rebuild* of the gems layer. Note that this only "re-assembles" the gem directory, no gems are being rebuilt. The actual cost in build time is negligible, but still present.

The solution listed here might not be correct, as it wouldn't include local directories used as gems. Though the general approach would be correct, e.g. use strictly only the inputs required for gems. Not sure how to best approach this.

**Comment by samueldr** [comment]
Oh, though it would make a needless layer upload for the gems layer. This is something the CAS (content-adressed store) would help solve, but this is not a solution for now.

**Comment by samueldr** [comment]
Discussed quickly, we will work under the assumption that no local gems are present, so it's fine to only work on Gemfile+Gemfile.lock

**Comment by jsierles** [comment]
Fixed in https://github.com/fly-apps/nix-base/pull/3
