### ISSUE TITLE
Bundix can't handle Gemfile with the ruby version specified there

### ISSUE THREAD

**Issue by jsierles** [fly-apps/rails-nix#2]
Most Gemfiles these days have the desired Ruby version embedded in `Gemfile` like:

`ruby "2.3.5"`

 Bundix incorrectly interprets this entry as a gem. We should either fix bundix, or work around it with the trick used here: https://github.com/nix-community/bundix/issues/81#issuecomment-882455018, or remove the line temporarily when running `bundix`. The line itself is useful to help us discover the target Ruby version.

**Comment by Matt-Yorkley** [comment]
It seems to build if the versions match? Nix's default Ruby version is `2.7.5`. If I set `ruby "2.7.5"` in the Gemfile, run `bundix -l` and then `nix-build` it doesn't complain.

**Comment by Matt-Yorkley** [comment]
Likewise with `ruby "3.0.3"` in the Gemfile, running `bundix -l`, then setting `ruby = pkgs.ruby_3_0` in `default.nix`... it builds successfully and the app runs with `3.0.3` :tada:

**Comment by Matt-Yorkley** [comment]
Aha... but it breaks when adding _new_ gems to the Gemfile. Ok, that seems like a `bundix` bug.

**Comment by jsierles** [comment]
Yeah - probably not hard to fix.

**Comment by Matt-Yorkley** [comment]
Hmmm okay, I've had a bit more success by passing the ruby package to bundix. This works:
1) Add a new gem
2) Install it locally with `bundle install`
3) run `bundix -l --ruby ruby_3_0` (referencing the Ruby nix package name)

**Comment by winston0410** [comment]
I have this exact issue right now, I have a gemfile like this:

```
source 'https://rubygems.org'

# security patch pins min versions
gem 'aws-sdk-s3'
gem 'loofah', '>= 2.2.3'
gem 'rack', '>= 2.0.6'

ruby '2.7.1'
```

And I run `bundix` like this:

```
nix-shell -p bundix --run "bundix --init --ruby=ruby_2_7"
```

And I got error like this:

```
[nix-shell:~/demo]$ rails
Traceback (most recent call last):
        3: from /nix/store/55rlx3hhr0l4z75qjf8dw40cya6dqjz7-lbh-income-api-bundler-env/bin/rails:19:in `<main>'
        2: from /nix/store/xvaflscg5fh6391lc8dfyrx899iq8frg-bundler-2.3.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler.rb:145:in `setup'
        1: from /nix/store/xvaflscg5fh6391lc8dfyrx899iq8frg-bundler-2.3.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/definition.rb:401:in `validate_runtime!'
/nix/store/xvaflscg5fh6391lc8dfyrx899iq8frg-bundler-2.3.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.6/lib/bundler/definition.rb:426:in `validate_ruby!': Your Ruby version is 2.7.5, but your Gemfile specified 2.7.1 (Bundler::RubyVersionMismatch)
```

How can I fix this version error?

**Comment by jsierles** [comment]
For our use case, we can probably ignore this by assuming that `bundix` is going to be run from a Nix environment defined by an _app spec_. The spec will be generated by a tool that detects the correct Ruby version from `Gemfile` and/or `.ruby-version`.
