### ISSUE TITLE
Make assets pre-compilation a discrete cacheable build and layer

### ISSUE THREAD

**Issue by jsierles** [fly-apps/rails-nix#22]
By default, only compile assets if `app/assets` has changed. Otherwise, reuse the previous build's cache. If possible, make triggering if this step configurable by allowing changes in other paths to trigger it.

**Comment by samueldr** [comment]
Assets pre-compilation is not a discrete step *yet*. It most likely can be, using `builtins.filterSource` or helpers made from `builtins.filterSource`.

**Comment by jsierles** [comment]
OK, sounds good 👍

**Comment by jsierles** [comment]
Implemented in https://github.com/fly-apps/nix-base/pull/3/commits/cdd35d244ce3b21bc2910e086da517e361744457
