### ISSUE TITLE
Choosing a strategy for changing nixpkgs versions

### ISSUE THREAD

**Issue by jsierles** [fly-apps/rails-nix#25]
The big plan, I think, is for Fly to have a 'main' nixpkgs pinned version. Whenever we decide to change this version, we'll kick off jobs that:

* Build and cache our custom software like Ruby patch versions, postgres gem, etc
* Run CI builds against real apps to ensure they build and deploy

**Question: What's a good strategy for deciding when to move the main pin forward? Is there already a best practice out there?** 

Presumably, security patches and such are going into nixpkgs all the time. So there are benefits to frequently moving the pin. But it will be impossible to cover all the possible issues that may pop up.

**Question: How should we manage versioning of our Nix builder code and nixpkgs?**

It feels to me that these should be versioned separately.

For nixpkgs, certainly it's desirable to get security patches and other important software upgrades automatically. But this necessarily would change the contents of your build, slow down deploys, and possibly cause problems. So it makes sense to pin apps to a Nixpkgs version. But we'd also need to version our builder code as we improve it. Let's think about how this could work.

Builder images are semantically versioned, so we could continue with what we're doing now - release new builders with new builder code. New builders get new code, old ones can be upgraded. So, an app could in theory move forward in nixpkgs, but use the same builder code.

Maybe we store Nix pins in our backend so apps can compare and upgrade if they choose?

**Comment by samueldr** [comment]
> **What's a good strategy for deciding when to move the main pin forward? Is there already a best practice out there?**

Yes, updating "ASAP" if possible it the best way to keep on top of security issues and bug fixes. Though this has to be done in a way that can be somewhat verifiable. Ideally enough automated testing to cover most scenarios.

> So there are benefits to frequently moving the pin. But it will be impossible to cover all the possible issues that may pop up.

I'm noting here that if we compare to some Docker image build practices, using `apt-get update` somewhere in that image build is likely just as problematic.

But with that said, end-user projects don't have to be updated in sync with your own updates. So they still would have the ability to revert to a previous version if it causes unforeseen consequences. Which is not easy to do with a "self-updating layer".

> **How should we manage versioning of our Nix builder code and nixpkgs?**

That's a good question. I don't think there's a unique good answer. Though with your description of the problem, I think you do have a good understanding of the problem space.

The builder infra could be released with a branching pattern. Imagine releases are made on a calendar base.

```
(letters represent abstracted Nixpkgs revisions)
fly-base 2022.03
    - 2022.03.aaaaa
    - 2022.03.bbbbb
    - ...
    - 2022.03.ggggg
    - 2022.03.hhhhh
fly-base 2022.05
    - 2022.05.ggggg
    - 2022.05.hhhhh
    - ...
    - 2022.05.ooooo
    - 2022.05.ppppp
```

Where there could be an overlap in Nixpkgs revision used for two distinct "versions" of the builders. Nothing forces you to do entirely linear releases. Though maintaining some versions in parallel comes at the cost of having to maintain these.

It also depends on what kind of SLA you want to provide to end-users.

**Comment by jsierles** [comment]
OK, I think the way you described makes the most sense. For now, we can start simple and just use whatever version is on the builders.

SLA feels far off - for now I think we just want to have a _rollback guarantee_. That will soon already be available at the deployed image level. So as long as we can ensure busted builds can also be rolled back, we'll be good for a while. And Nix already guarantees this.

**Comment by jsierles** [comment]
Also, you're right about all the Docker points. I wasn't putting down Nix here, just thinking out loud about what challenges we may face if we're entering the nix space as a code/cache maintainer. Certainly a lower surface area than 'Random Docker images maintaner' :)

**Comment by jsierles** [comment]
One concern is that newer versions of nixpkgs could break our module implementation, as we're seeing right now. So we should setup CI on `nix-base` to ensure the modules load correctly as we move forward.

Closing this for now in favor of more specific issues.
