### ISSUE TITLE
Update the `pg` gem in Nixpkgs to depend on `postgresql.lib` to reduce the closure size

### ISSUE THREAD

**Issue by grahamc** [fly-apps/rails-nix#6]
The pg gem depends on postgresql the (server), perl, among other things. This adds quite a lot of heft to the closure.

From #4:

One easyish fix would be to switch the `pg` gem to depend on `postgresql.lib` instead of `postgresql`. It has a large tree of dependencies including systemd.

```
[nix-shell:~/.../rails-nix]$ nix --extra-experimental-features nix-command why-depends -f ./. packed-app pkgs.perl | cat
trace: Using default Nixpkgs revision 'c28fb0a4671ff2715c1922719797615945e5b6a0'...
warning: Git tree '/Users/samuel/DetSys/2022-fly/rails-nix' is dirty
/nix/store/2zajgla3b3bw47rbnyy10m17nkr90w8q-packed-rails-nix-0.0.0
└───tmp/cache/bootsnap/compile-cache-iseq/08/d8490ca05c810a: ….................E.../nix/store/hnm67idngkqkwg3ap02jkh142sqwvc67-ruby2.7.5-pg-1.3.1/lib/ruby/gem…
    → /nix/store/hnm67idngkqkwg3ap02jkh142sqwvc67-ruby2.7.5-pg-1.3.1
    └───lib/ruby/gems/2.7.0/build_info/pg-1.3.1.info: …--with-pg-config=/nix/store/5w35mb5b4a26rwac1qa4rbwdnwfyrx1w-postgresql-13.5/bin/pg_config.…
        → /nix/store/5w35mb5b4a26rwac1qa4rbwdnwfyrx1w-postgresql-13.5
        └───bin/pg_config: ….2-dev/lib/pkgconfig:/nix/store/xy347fibaxrc58xb8l09y88r6qqjyxsx-openssl-1.1.1m-dev/lib/pkgconfi…
            → /nix/store/xy347fibaxrc58xb8l09y88r6qqjyxsx-openssl-1.1.1m-dev
            └───nix-support/propagated-build-inputs: … /nix/store/3vy7p7m0a38ip1dlad0pk0ydd3plrgyy-openssl-1.1.1m-bin /nix/store/6…
                → /nix/store/3vy7p7m0a38ip1dlad0pk0ydd3plrgyy-openssl-1.1.1m-bin
                └───bin/c_rehash: …#!/nix/store/y84babjpa0ngq62pqvygsajscx7mlnks-perl-5.34.0/bin/perl..# WARNING…
                    → /nix/store/y84babjpa0ngq62pqvygsajscx7mlnks-perl-5.34.0
```

Here's an issue discussing this: https://github.com/NixOS/nixpkgs/issues/61580

--

We may want to consider prohibit the gem's derivation from depending on certain run-time dependencies like perl. This would make it less likely for this situation to occur in the future.

**Comment by jsierles** [comment]
Just curious - why would we not just make the gem dependent on postgres.lib in nixpkgs? There is no requirement at all to have the full postgres installation for this library to work.

**Comment by samueldr** [comment]
> Just curious - why would we not just make the gem dependent on postgres.lib in nixpkgs

Turns out that in practice it already is. There's only `.info` files from the gem build arguments accidentally rooting the build-time dependencies in the gem build.
