### ISSUE TITLE
Skip inclusion of gems in the development/test groups

### ISSUE THREAD

**Issue by grahamc** [fly-apps/rails-nix#8]
From #4:

This is standard practice for Ruby deployments. It doesn't seem to be supported by Bundix directly, but probably can be done easily, maybe with `bundleEnv`.

**Comment by samueldr** [comment]
AFAICT It should already be including only the `"default"` group:

 - https://github.com/NixOS/nixpkgs/blob/5c4d9d0e50e7a9158a8ca976dea58d3ec95f9c56/pkgs/development/ruby-modules/bundler-env/default.nix#L11

Though I'm unsure about whether that is working like I expect it or not:

 - https://github.com/fly-apps/rails-nix/blob/4cf7917f319b0f60aedc282501d09c4b069306cb/gemset.nix#L165-L175

```
[nix-shell:~/.../rails-nix]$ find $(nix-build -A app.gems) -iname '*capybara*'
/nix/store/0hnxrd1i0vkha5ccnbhxxnkqqcclvfph-rails-nix-gems/lib/ruby/gems/2.7.0/specifications/capybara-3.36.0.gemspec
/nix/store/0hnxrd1i0vkha5ccnbhxxnkqqcclvfph-rails-nix-gems/lib/ruby/gems/2.7.0/gems/capybara-3.36.0
```

**Comment by samueldr** [comment]
Given that forcing `groups = ["default"]` to the `bundlerEnv` call removes `capybara` from the gems output, I figure it's not working as I understand it.

**Comment by samueldr** [comment]
This is because the default `groups` isn't used here:

 - https://github.com/NixOS/nixpkgs/blob/5c4d9d0e50e7a9158a8ca976dea58d3ec95f9c56/pkgs/development/ruby-modules/bundler-env/default.nix#L41-L42
 - https://github.com/NixOS/nixpkgs/blob/5c4d9d0e50e7a9158a8ca976dea58d3ec95f9c56/pkgs/development/ruby-modules/bundled-common/default.nix#L21

**Comment by samueldr** [comment]
No PRs opened, as this might not be fixable on our end, and might require work on the Nixpkgs end to fix problems.

 - https://github.com/fly-apps/rails-nix/commits/fix/8-gem-groups

See how there's a reverted commit to "fix" the image build, it's not sufficient as when running the same underlying issue surfaces. (And anyway felt like a bad fix.)

The issue, AFAIUI is that if we only install some gem groups, `bundle` for `bundle exec` is not aware of it, and will get annoyed.

```
Could not find debug-1.4.0, web-console-4.2.0, capybara-3.36.0, selenium-webdriver-4.1.0, webdrivers-5.0.0 in any of the sources
Run `bundle install` to install missing gems.
```

This *might* be fixed if the store path holding the `Gemfile{,.lock}` files had a `.bundle/config` with the config equivalent to running `bundle config set --local without test development`. Though this doesn't "scale" as a solution, we can't know what groups to add to `BUNDLE_WITHOUT`.

Note that we could handle it locally, but it would require *somehow* wrapping anything running in that environment to be wrapped with the `BUNDLE_WITHOUT` environment variable, which would need to list the remainder of `allGroups - [ "default" ]`. The latter part is doable with `gemset.nix`, but wrapping all with `BUNDLE_WITHOUT` is not a reliable solution.

The only reliable solution would be to get bundler to see its `.bundle/config` for the given gemset, which requires some work within Nixpkgs.
